[package]
name = "toggle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
limine = "0.3.1"
noto-sans-mono-bitmap = "0.3.0"
